version: '3'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  odoo:
    image: odoo:15
    container_name: odoo
    restart: always
    depends_on:
      - postgres
    ports:
      - "8069:8069"
      - "8072:8072"
    environment:
      - HOST=postgres
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - ./etc/odoo:/etc/odoo
      - ./data/addons:/mnt/extra-addons
      - ./data/odoo:/var/lib/odoo


