version: '3'

services:
  postgres:
    image: postgres:9.5.25
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  odoo:
    image: odoo:13.0
    container_name: odoo
    restart: always
    depends_on:
      - postgres
    ports:
      - "8069:8069"
      - "8072:8072"
    environment:
      HOST: postgres
      USER: ${POSTGRES_USER}
      PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./etc/odoo:/etc/odoo
      - ./data/addons:/mnt/extra-addons
      - ./data/odoo:/var/lib/odoo

  gadmin:
      image: dpage/pgadmin4:4.6
      container_name: pgadmin4
      restart: always
      environment:
         PGADMIN_DEFAULT_EMAIL: admin
         PGADMIN_DEFAULT_PASSWORD: miclave
         PGADMIN_LISTEN_PORT: 80
      ports:
         - "8080:80"
      links:
         - "postgres:pgsql-server"

  nginx:
      image: nginx:latest
      container_name: nginx
      depends_on:
        - odoo
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      ports:
        - 80:80
        - 443:443